# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/code_ownership/all/code_ownership.rbi
#
# code_ownership-1.22.0

module CodeOwnership
  def for_backtrace(*args, **, &blk); end
  def for_class(*args, **, &blk); end
  def for_file(*args, **, &blk); end
  def for_package(*args, **, &blk); end
  def self.bust_caches!(*args, **, &blk); end
  def self.remove_file_annotation!(*args, **, &blk); end
  def validate!(*args, **, &blk); end
  extend CodeOwnership
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CodeOwnership::Cli
  def self.run!(argv); end
  def self.validate!(argv); end
end
module CodeOwnership::Private
  def self.bust_caches!(*args, **, &blk); end
  def self.configuration(*args, **, &blk); end
  def self.file_annotations_mapper(*args, **, &blk); end
  def self.files_by_mapper(*args, **, &blk); end
  def self.find_team!(*args, **, &blk); end
  def self.mappers(*args, **, &blk); end
  def self.path_from_klass(*args, **, &blk); end
  def self.tracked_files(*args, **, &blk); end
  def self.validate!(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CodeOwnership::Private::Configuration < T::Struct
  def __t_props_generated_deserialize(*args, **); end
  def __t_props_generated_serialize(*args, **); end
  def js_package_paths; end
  def owned_globs; end
  def self.fetch(*args, **, &blk); end
  def self.inherited(s); end
  def self.js_package_paths(*args, **, &blk); end
  def skip_codeowners_validation; end
  def unowned_globs; end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
  extend T::Sig
end
module CodeOwnership::Private::TeamPlugins
end
class CodeOwnership::Private::TeamPlugins::Ownership < Teams::Plugin
  def owned_globs(*args, **, &blk); end
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CodeOwnership::Private::TeamPlugins::Github < Teams::Plugin
  def github(*args, **, &blk); end
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CodeOwnership::Private::TeamPlugins::Github::GithubStruct < Struct
  def do_not_add_to_codeowners_file; end
  def do_not_add_to_codeowners_file=(_); end
  def self.[](*arg0); end
  def self.inspect; end
  def self.keyword_init?; end
  def self.members; end
  def self.new(*arg0); end
  def team; end
  def team=(_); end
end
module CodeOwnership::Private::ParseJsPackages
  def self.all(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CodeOwnership::Private::ParseJsPackages::Package < T::Struct
  def __t_props_generated_deserialize(*args, **); end
  def __t_props_generated_serialize(*args, **); end
  def directory(*args, **, &blk); end
  def metadata; end
  def name; end
  def self.from(*args, **, &blk); end
  def self.inherited(s); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
  extend T::Sig
end
module CodeOwnership::Private::Validations
end
module CodeOwnership::Private::Validations::Interface
  def validation_errors(*args, **, &blk); end
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CodeOwnership::Private::Validations::FilesHaveOwners
  def validation_errors(*args, **, &blk); end
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include CodeOwnership::Private::Validations::Interface
end
class CodeOwnership::Private::Validations::GithubCodeownersUpToDate
  def codeowners_file_lines(*args, **, &blk); end
  def validation_errors(*args, **, &blk); end
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include CodeOwnership::Private::Validations::Interface
end
class CodeOwnership::Private::Validations::FilesHaveUniqueOwners
  def validation_errors(*args, **, &blk); end
  extend T::Helpers
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include CodeOwnership::Private::Validations::Interface
end
module CodeOwnership::Private::OwnershipMappers
end
module CodeOwnership::Private::OwnershipMappers::Interface
  def bust_caches!(*args, **, &blk); end
  def codeowners_lines_to_owners(*args, **, &blk); end
  def description(*args, **, &blk); end
  def map_file_to_owner(*args, **, &blk); end
  def map_files_to_owners(*args, **, &blk); end
  extend T::Helpers
  extend T::Private::Abstract::Hooks
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class CodeOwnership::Private::OwnershipMappers::FileAnnotations
  def bust_caches!(*args, **, &blk); end
  def codeowners_lines_to_owners(*args, **, &blk); end
  def description(*args, **, &blk); end
  def file_annotation_based_owner(*args, **, &blk); end
  def map_file_to_owner(*args, **, &blk); end
  def map_files_to_owners(*args, **, &blk); end
  def remove_file_annotation!(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include CodeOwnership::Private::OwnershipMappers::Interface
end
class CodeOwnership::Private::OwnershipMappers::TeamGlobs
  def bust_caches!(*args, **, &blk); end
  def codeowners_lines_to_owners(*args, **, &blk); end
  def description(*args, **, &blk); end
  def map_file_to_owner(*args, **, &blk); end
  def map_files_to_owners(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include CodeOwnership::Private::OwnershipMappers::Interface
end
class CodeOwnership::Private::OwnershipMappers::PackageOwnership
  def bust_caches!(*args, **, &blk); end
  def codeowners_lines_to_owners(*args, **, &blk); end
  def description(*args, **, &blk); end
  def map_file_to_owner(*args, **, &blk); end
  def map_file_to_relevant_package(*args, **, &blk); end
  def map_files_to_owners(*args, **, &blk); end
  def owner_for_package(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include CodeOwnership::Private::OwnershipMappers::Interface
end
class CodeOwnership::Private::OwnershipMappers::JsPackageOwnership
  def bust_caches!(*args, **, &blk); end
  def codeowners_lines_to_owners(*args, **, &blk); end
  def description(*args, **, &blk); end
  def map_file_to_owner(*args, **, &blk); end
  def map_file_to_relevant_package(*args, **, &blk); end
  def map_files_to_owners(*args, **, &blk); end
  def owner_for_package(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
  include CodeOwnership::Private::OwnershipMappers::Interface
end
class CodeOwnership::InvalidCodeOwnershipConfigurationError < StandardError
end
