# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/parse_packwerk/all/parse_packwerk.rbi
#
# parse_packwerk-0.9.0

module ParsePackwerk
  def self.all(*args, **, &blk); end
  def self.find(*args, **, &blk); end
  def self.packages_by_name(*args, **, &blk); end
  def self.write_package_yml!(*args, **, &blk); end
  def self.yml(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class ParsePackwerk::Violation < T::Struct
  def __t_props_generated_deserialize(*args, **); end
  def __t_props_generated_serialize(*args, **); end
  def class_name; end
  def dependency?(*args, **, &blk); end
  def files; end
  def privacy?(*args, **, &blk); end
  def self.inherited(s); end
  def to_package_name; end
  def type; end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
  extend T::Sig
end
class ParsePackwerk::DeprecatedReferences < T::Struct
  def __t_props_generated_deserialize(*args, **); end
  def __t_props_generated_serialize(*args, **); end
  def pathname; end
  def self.for(*args, **, &blk); end
  def self.from(*args, **, &blk); end
  def self.inherited(s); end
  def violations; end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
  extend T::Sig
end
class ParsePackwerk::Package < T::Struct
  def __t_props_generated_deserialize(*args, **); end
  def __t_props_generated_serialize(*args, **); end
  def dependencies; end
  def directory(*args, **, &blk); end
  def enforce_dependencies; end
  def enforce_privacy; end
  def enforces_dependencies?(*args, **, &blk); end
  def enforces_privacy?(*args, **, &blk); end
  def metadata; end
  def name; end
  def self.from(*args, **, &blk); end
  def self.inherited(s); end
  def yml(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
  extend T::Sig
end
class ParsePackwerk::Configuration < T::Struct
  def __t_props_generated_deserialize(*args, **); end
  def __t_props_generated_serialize(*args, **); end
  def exclude; end
  def package_paths; end
  def self.excludes(*args, **, &blk); end
  def self.fetch(*args, **, &blk); end
  def self.inherited(s); end
  def self.package_paths(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Props::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Plugin::ClassMethods
  extend T::Props::Serializable::ClassMethods
  extend T::Sig
end
class ParsePackwerk::PackageSet
  def self.exclude_path?(*args, **, &blk); end
  def self.from(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
class ParsePackwerk::MissingConfiguration < StandardError
  def initialize(*args, **, &blk); end
  extend T::Private::Methods::MethodHooks
  extend T::Private::Methods::SingletonMethodHooks
  extend T::Sig
end
