inherit_from: .rubocop_todo.yml

inherit_mode:
  merge:
    - Include

plugins:
  - rubocop-rspec
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Layout/LineLength:
  Enabled: false

Naming/BlockForwarding:
  Enabled: false

Style/Documentation:
  Enabled: false
